#!/usr/bin/env php
<?php
if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

define('LAUNCHER_DIR', __DIR__);

$content = file_get_contents(__DIR__ . DIRECTORY_SEPARATOR . 'composer.json');
$composer = json_decode($content,true);
$version = $composer['version'];
$name = $composer['displayName'];


$app = new Symfony\Component\Console\Application($name, $version);
#$app->add(new Mosaiqo\Launcher\Console\ConfigCommand);
#$app->add(new Mosaiqo\Launcher\Console\NewCommand);
#$app->add(new Mosaiqo\Launcher\Console\StartCommand);
#$app->add(new Mosaiqo\Launcher\Console\StopCommand);
#$app->add(new Mosaiqo\Launcher\Console\OpenCommand);
#$app->add(new Mosaiqo\Launcher\Console\ServiceAddCommand);

# Launcher Commands
$app->add(new Mosaiqo\Launcher\Console\Launcher\ConfigCommand);

# Project Commands
$app->add(new Mosaiqo\Launcher\Console\Projects\NewCommand);
$app->add(new Mosaiqo\Launcher\Console\Projects\StartCommand);
$app->add(new Mosaiqo\Launcher\Console\Projects\ListCommand);
$app->run();